### ISSUE TITLE
"Uncaught TypeError: Array.from is not a function" in Chrome

### ISSUE THREAD

**Issue by mythmon** [mythmon/edwin#72]
```
Error loading data: TypeError: Array.from is not a function
    at loadBlockerBugs (http://edwin.mozilla.io/static/js/client.f9114b4e168f.js:35:4018)
    at http://edwin.mozilla.io/static/js/client.f9114b4e168f.js:35:1702
(anonymous function)    @   client.f9114b4e168f.js:38
```

This is preventing the Timeline page from loading on Chrome.

**Comment by willkg** [comment]
Pretty sure that's an ES6 thing. I thought that sort of thing would get compiled down to an ES5 equivalent.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/from

We should change it to something else if it's causing problems. I'm just kind of surprised.

**Comment by willkg** [comment]
@mythmon found this: https://github.com/babel/babel/issues/646
